package com.nat.change;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * @author Cenzo
 * @version 1.0
 * @since 2019-10-15
 */
@SpringBootApplication
public class ChangeApplication {

	/**
	 * The application runner. This is generated by Spring framework and has not been modified.
	 *
	 * @param args
	 */
	public static void main(String[] args) {
		SpringApplication.run(ChangeApplication.class, args);
	}

}
